version: '3'

services:
  bot:
    build: ./dockerfiles/bot
    volumes:
      - ./bot:/opt
    networks:
      - nw_fleet
    env_file:
      - envs/bot.env
    restart: always

networks:
  nw_fleet:
    driver: bridge
